function settings = OneClickSettings() 
    settings = struct(...
        'RootDir','C:\Midlertidig_Lagring\EpiOneClick',...
        'EeglabPath', 'C:\Midlertidig_Lagring\eeglab' ...        
    );    
end 