function settings = EpiOneClickSettings() 
    settings = struct(...
        'RootDir','C:\Midlertidig_Lagring\EpiOneClick',...
        'EeglabPath', 'C:\Midlertidig_Lagring\eeglab', ...   
        'SaveFolder', '\\ihelse.net\Forskning\hbe\2017-01512\2019\EivindArtikkel3\data\00-Pilot_bugfixed\eivaan annotations' ...
    );    
end 