function settings = EpiOneClickSettings() 
    settings = struct(...
        'RootDir','C:\Midlertidig_Lagring\EpiOneClick',...
        'EeglabPath', 'C:\Midlertidig_Lagring\eeglab', ...   
        'SaveFolder', 'C:\Midlertidig_Lagring\EpiOneClick\ExternalDatasetEivaan', ...
        'Rater', 'eivaan', ...
        'Project', 'ext' ...
    );    
end 